### ISSUE TITLE
Wrong Readme

### ISSUE THREAD

**Issue by danielalvarenga** [atongen/cript#1]
In this case
Cript::Simple.new({**private_key_path**: "-----BEGIN RSA PRIVATE KEY-----\n3f4q..."})
the key is
Cript::Simple.new({**private_key_content**: "-----BEGIN RSA PRIVATE KEY-----\n3f4q..."})

**Comment by atongen** [comment]
Thank you! Addressed in c246e1f30fb467796525170bba91005e8f1d42fa
